### PR TITLE
V1 - New Layout Elements

### PR DESCRIPTION
**Pull request by blforce**
New layout elements, now with Layout prefixes.

### CODE REVIEW

**Comment by blforce** [comment]
For some reason the dist folder is getting committed...

**Comment by blforce** [comment]
Okay, it should be ready now. 👍

**Comment by posva** [comment]
Haha, you also changed your picture in the meantime.
I'll check this tomorrow. Thank you a lot! 👏

**Comment by posva** [comment]
This got closed because I moved the branch v1 to develop, could you please reopen the PR?
I'm sorry I couldn't take a look 😓

**Pull request closed without merging**
