### PR TITLE
Add no-focus-trap prop for dialog

### LINKED ISSUE #92: Dialogs, option to disable focus-trap
Hello Eduardo, a property to disable `focus-trap` in MdlDialog would be useful in many cases.
I'm having trouble with `md-date-time-picker` that render outside MdlDialog.

Great Job! Greetings from Argentina.

### PR DESCRIPTION
**Pull request by dabroder**
Resolves #92

### CODE REVIEW

**Comment by dsl101** [comment]
Would you need to watch for that prop changing dynamically, and instantiate `this._focusTrap` regardless on `mounted()`, but only call it if the prop is true? I don't use dialogs, so perhaps I misunderstood how they work...

**Comment by dsl101** [comment]
Does that solve it? Suppose I create it with `no-focus-trap', then on `mounted()`, `this._focusTrap` will not be initialised. But if I then change that prop to `true`, `this._nofocusTrap` will still not exist, and so whilst the guard will prevent trying to access something `undefined`, it still won't work as the user might expect.

**Comment by posva** [comment]
@dsl101 I didn't hit the commit button 😆

**Comment by posva** [comment]
Thanks @dabroder

**Pull request merged**
