### PR TITLE
Update card.vue - triggerActionsEvent

### PR DESCRIPTION
**Pull request by nckvh**
add @click="triggerActionsEvent" to the "else" portion of the actions slot's button.

currently, there is no @click bound to the button, and the function does not fire.

### CODE REVIEW

**Comment by posva** [comment]
Hi @nckvh Thanks for taking the time to look at this. I couldn't even answer your mail!
If you can add a test that'd be perfect, if not I can add it myself tomorrow and release a version

**Comment by nckvh** [comment]
Hey @posva I just took a look in the tests folder, and it seems there is alredy a test written for this function. Is this already correct?

` it('dispatchs events for actions button', (done) => {
    let called = false
    vm.$once('someEventName', () => {
      called = true
    })
    vm.$refs.card.triggerActionsEvent()
    vm.nextTick()
    .then(() => {
      called.should.be.true
      return vm.nextTick()
    }).then(done, done)
  })`

**Comment by posva** [comment]
The test in actually bad because it doesn't click the button >.<
Thanks for pointing this out. I'm fixing it

**Comment by posva** [comment]
Merging and adding the test afterwards
Thanks @nckvh !

**Comment by nckvh** [comment]
anytime! thanks for being so responsive!

**Pull request merged**
