### PR TITLE
Added position config for tooltips

### PR DESCRIPTION
**Pull request by pksunkara**
I am surprised that some components are only half done. I reckon every option from getmdl.io should be supported.

### CODE REVIEW

**Comment by posva** [comment]
@pksunkara Unfortunately, yes, some are not finished 🙁 
I don't have enough time to focus on this so I keep adding things from time to time
I even started working on a v2 for material components web (which is the continuation of material design lite) and focused on having something easy to contribute to (it's the mdc branch). I'm still missing the docs. Not sure about what to do with that yet. But I'd like to create a team, move the repo to an organisation and have some help to maintain it. If you want to help out, I can add you once I create it

**Comment by posva** [comment]
I cannot release right now so I'll do it tomorrow

**Comment by pksunkara** [comment]
I never knew about mdc until now. I think we should focus our efforts there instead of mdl. I am okay with the plan to move to org and help maintaining it.

**Comment by posva** [comment]
Me too. I'm glad to hear that 🙂 I'll find the time to create the org and invite you

**Comment by posva** [comment]
Released a new version

**Pull request merged**
