### PR TITLE
Autosize support for Textfield

### PR DESCRIPTION
**Pull request by Chrissi2812**
Integrated [jackmoore/autosize](https://github.com/jackmoore/autosize) for the textfields

```html
<mdl-textfield autosize textarea ></mdl-textfield>
```

p.s i don't know how to write a test for it 😢  but it's working.

### CODE REVIEW

**Comment by posva** [comment]
Hey, thanks for your interest in the project!
I think this is something that should be done in userland. I haven't tested it but since a user may want to use autosize others elements, including it in vue-mdl will end up adding it twice.
Let me create a fiddle for this

**Comment by posva** [comment]
@Chrissi2812  This got closed automatically because I moved the branch v1 to develop. To use autosize, you should be able to create a directive, though

**Comment by Chrissi2812** [comment]
@posva thanks for your reply, I'm new to Vue.js so i didn't know about custom directives. So I'm glad you mentioned them.

**Comment by posva** [comment]
@Chrissi2812 No worries. The guide has a section here: https://vuejs.org/v2/guide/custom-directive.html
The relevant hook should be `inserted`

**Pull request closed without merging**
