### PR TITLE
Don't show the badge if data-badge is number and 0

### PR DESCRIPTION
**Pull request by Atinux**

### CODE REVIEW

**Comment by posva** [comment]
Hey,
Thanks for the PR. Being able to deactivate the data-badge is indeed a nice idea. I will add some commits to the PR in order to fix the lint and make it more flexible before merging it

**Comment by Atinux** [comment]
Thank for doing this project :+1:

**Comment by posva** [comment]
Thanks for supporting it!

**Comment by posva** [comment]
@Atinux I implemented a version of this in https://github.com/posva/vue-mdl/commit/ab2fabb365eb7289644d05edf7ca94d66a3c4b23
You can now use the `number` modifier to get the behaviour you asked for.

Sorry for not actually merging you PR, I ended up changing too much things, I hope this doesn't bother you

**Comment by Atinux** [comment]
No problem, thanks for this repository man!

**Pull request closed without merging**
