### PR TITLE
V1 layouts

### PR DESCRIPTION
**Pull request by posva**
@blforce I created this from your branch. I really want to take the time to review it properly so I'll probably do it next week

### CODE REVIEW

**Comment by blforce** [comment]
Sorry I missed your other messages. Did you need me to change anything right now?

**Comment by posva** [comment]
No, don't worry @blforce I still have to check this. Haven't found the time yet

**Comment by posva** [comment]
@blforce I removed the tabs because the behaviour was really weird and was using a lot of hacks but kept all the rest.
I also had to convert the files to unix format 😆 
Thanks for the work, it really helped 😄

**Comment by pksunkara** [comment]
I guess docs are missing for this?

**Comment by posva** [comment]
@pksunkara yes. They haven't been written yet, but you can check the tests to see how to use them 🙂

**Comment by pksunkara** [comment]
@posva Where can I catch you so that I can discuss some changes I want to contribute to vue-mdl?

**Comment by posva** [comment]
There's a gitter chat: https://gitter.im/posva/vue-mdl?utm_source=badge&utm_medium=badge&utm_campaign=pr-badgel

**Pull request merged**
