### PR TITLE
create a custom dialogs component for vue-mdl

### PR DESCRIPTION
**Pull request by Gemerz**
Hi posva, This is awesome framework with mdl make me easy to develop vue project.  thanks.

### CODE REVIEW

**Comment by posva** [comment]
Hello!

Thanks for the contribution! I'm doing a review later today. I already saw some issues about manual event listeners added :stuck_out_tongue: If you can already change that, that'd be great

Also the commits are not attributed to your profile :cry: I can help you with that if you wish

**Comment by posva** [comment]
@Gemerz just letting you know that I'm writing on top of you work to get this merged

**Comment by posva** [comment]
Although a lot of your code has been replaced, it helped me a lot, so really thank you! :smile:

**Comment by Gemerz** [comment]
You welcome:smile:. So recently I working on a uploader component with mdl style,using FileReader and TJ [s3.js](https://github.com/tj/s3.js) 's some thought,I think that would work two way, upload to cloud or local server with preview.

**Pull request closed without merging**
